name: Tox tests

on: [push, pull_request]

jobs:
  py27:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py27 -vv
  py37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py37 -vv
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e black -vv
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e flake8 -vv
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs -vv
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py37
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          verbose: true
